### ISSUE TITLE
Questplay is broken since 1.7.0 (expect for mac m1 users) 

### ISSUE THREAD

**Issue by ncoquelet** [Nodeguardians/ng-questplay#57]
Hello,

A developer using a Mac M1 accidentally deleted platform-specific solidity-analyzer libraries, causing issues for users on other platforms 😆 
This occurred due to the behavior outlined in [NPM issue #4828](https://github.com/npm/cli/issues/4828#issuecomment-1570697122).

In summary, it's crucial to always delete both the package-lock.json AND node_modules together before regenerating a fresh package-lock.json 😉

**Comment by ncoquelet** [comment]
https://github.com/Nodeguardians/ng-questplay/commit/f87a7b91d11f83f0eba458e0672c224684ebe3a4#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L1102
(you need to load package_lock.json diff)

**Comment by hroussille** [comment]
This should be fixed in 1.7.1, you can update already !

**Comment by ncoquelet** [comment]
I confirm, fixed in my case
I closed
